### ISSUE TITLE
Lemurian Ship erroneously locked behind Gabomba Statue

### ISSUE THREAD

**Issue by Karanum** [MarvinXLII/emotracker-golden-sun-tla-randomizer#1]
The Lemurian Ship location in the tracker is locked behind clearing Gabomba Statue, though this isn't required to enter the ship in the latest version of the randomizer (v0.2.2b)

It is likely that recruiting Piers is the trigger for entering the ship rather than clearing Gabomba.

**Comment by MarvinXLII** [comment]
It turned out to be a minor bug in the randomizer itself, rather than a bug in the tracker logic. I fixed it, and will be sure to include it in the next randomizer update.
